---
- name: Check SecureBoot and record IP if enabled
  hosts: all
  become: true  # To run the tasks as a superuser if needed
  tasks:
    - name: Check if Secure Boot is enabled
      shell: "mokutil --sb-state"
      register: secureboot_status
      ignore_errors: true  # in case mokutil is not installed

    - name: Fail if mokutil is not available
      fail:
        msg: "mokutil command is not found on the system, unable to check Secure Boot status"
      when: EFI variables are not supported on this system

    - name: Extract Secure Boot status
      set_fact:
        secureboot_enabled: "{{ 'SecureBoot' in secureboot_status.stdout }}"

    - name: Get the server IP address
      command: "hostname -I"
      register: server_ip
      when: secureboot_enabled

    - name: Write IP to secureboot.txt if Secure Boot is enabled
      copy:
        content: "{{ server_ip.stdout }}"
        dest: "/path/to/secureboot.txt"
      when: secureboot_enabled
