---
- name: Print using Vars in Ansible
  hosts: localhost
  vars_file:
    - Automate.sh/sample-vars.yml

  vars:
    URL: Play.example.com

  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL -"{{URL}}", URL1 -"{{URL1}}"
