---
- name: Print using Vars in Ansible
  hosts: localhost
  vars_files:
    - Automate.sh/sample-vars.yml

  vars:
    URL: Play.example.com

  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "URL - {{ URL }}, URL1 - {{ URL1 | default('undefined') }}"
